import {
    Box,
    BoxProps,
    CloseButton,
    Drawer,
    DrawerContent,
    Flex,
    FlexProps,
    Icon,
    IconButton,
    Image,
    useColorModeValue,
    useDisclosure,
} from "@chakra-ui/react";
import DrawerComponent from "@components/Drawer";
import { SIZES } from "@constants/index";
import "@public/logo.svg";
import { selectAuth } from "@redux/features/authSlice";
import { useAppSelector } from "@redux/hooks";
import Head from "next/head";
import Link from "next/link";
import React from "react";
import { IconType } from "react-icons";
import { AiOutlineShoppingCart, AiOutlineUserSwitch } from "react-icons/ai";
import { BiStore } from "react-icons/bi";
import { FiMenu } from "react-icons/fi";
import { MdOutlineFoodBank } from "react-icons/md";

interface LinkItemProps {
    name: string | any;
    icon: IconType;
    url: string;
}

export const Layout: React.FC<any> = ({ children }) => {
    const { isOpen, onOpen, onClose } = useDisclosure();
    const cartDrawer = useDisclosure();

    return (
        <Box minH="100vh" bg={useColorModeValue("gray.100", "gray.900")}>
            <SidebarContent
                onClose={onClose}
                display={{ base: "none", md: "block" }}
            />
            <Drawer
                isOpen={isOpen}
                placement="left"
                onClose={onClose}
                size="full">
                <DrawerContent>
                    <SidebarContent onClose={onClose} />
                </DrawerContent>
            </Drawer>
            <MobileNav onOpen={onOpen} display={{ base: "flex", md: "none" }} />
            <Flex
                ml={{ base: 0, md: 60 }}
                px={{ base: 4, md: 24 }}
                height="20"
                alignItems="center"
                bg={useColorModeValue("white", "gray.900")}
                borderBottomWidth="1px"
                borderBottomColor={useColorModeValue("gray.200", "gray.700")}
                justifyContent="flex-start">
                <Icon
                    as={AiOutlineShoppingCart}
                    onClick={cartDrawer.onOpen}
                    boxSize={10}
                    color="green.400"
                    cursor={"pointer"}
                />
            </Flex>
            <Box ml={{ base: 0, md: 80 }} p="4">
                {React.cloneElement(children, { onClose })}
            </Box>
            <DrawerComponent
                isOpen={cartDrawer.isOpen}
                onClose={cartDrawer.onClose}
            />
        </Box>
    );
};

interface SidebarProps extends BoxProps {
    onClose: () => void;
}

const SidebarContent = ({ onClose, ...rest }: SidebarProps) => {
    const { username } = useAppSelector(selectAuth);

    const LinkItems: LinkItemProps[] = [
        {
            name: username ? username : "Guest",
            url: "/",
            icon: AiOutlineUserSwitch,
        },

        { name: "Shops", url: "/shops", icon: BiStore },
        { name: "Products", url: "/products", icon: MdOutlineFoodBank },
    ];

    return (
        <>
            <Head>
                <title>next</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Box
                bg={useColorModeValue("white", "gray.900")}
                borderRight={"1px"}
                borderRightColor={useColorModeValue("gray.200", "gray.700")}
                w={{ base: "full", md: 80 }}
                position={"fixed"}
                h={"full"}
                {...rest}>
                <Flex
                    h="20"
                    m="8"
                    justifyContent={{ base: "space-between", md: "center" }}>
                    <Box boxSize={"6rem"}>
                        <Image src={"logo.svg"} w={"full"} h={"full"} />
                    </Box>
                    <CloseButton
                        display={{ base: "flex", md: "none" }}
                        onClick={onClose}
                    />
                </Flex>
                {LinkItems.map((link) => (
                    <NavItem key={link.name} icon={link.icon} url={link.url}>
                        {link.name}
                    </NavItem>
                ))}
            </Box>
        </>
    );
};

interface NavItemProps extends FlexProps {
    icon: IconType;
    children: React.ReactNode;
    url: string;
}
const NavItem = ({ icon, url, children, ...rest }: NavItemProps) => {
    return (
        <Link href={url} style={{ textDecoration: "none" }}>
            <Flex
                border={"1px"}
                p={"4"}
                m={"4"}
                alignItems={"center"}
                justifyItems={"center"}
                borderRadius={"lg"}
                role={"group"}
                cursor={"pointer"}
                _hover={{
                    bg: "cyan.400",
                    color: "white",
                }}
                fontSize={SIZES}
                {...rest}>
                {icon && (
                    <Icon
                        mr="4"
                        _groupHover={{
                            color: "white",
                        }}
                        as={icon}
                    />
                )}
                {children}
            </Flex>
        </Link>
    );
};

interface MobileProps extends FlexProps {
    onOpen: () => void;
}
const MobileNav = ({ onOpen, ...rest }: MobileProps) => {
    return (
        <Flex
            ml={{ base: 0, md: 60 }}
            px={{ base: 4, md: 24 }}
            height="20"
            alignItems="center"
            bg={useColorModeValue("white", "gray.900")}
            borderBottomWidth="1px"
            borderBottomColor={useColorModeValue("gray.200", "gray.700")}
            justifyContent="flex-start"
            {...rest}>
            <IconButton
                variant="outline"
                onClick={onOpen}
                aria-label="open menu"
                icon={<FiMenu />}
            />
        </Flex>
    );
};
